import React, { useEffect, useState, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion, useScroll, useSpring } from 'framer-motion';
import { Helmet } from 'react-helmet-async';
import SafeIcon from '@/common/SafeIcon';
import { getLatestPosts, stripHtml } from '@/lib/api';
import AutomationCalculator from '@/components/intel/AutomationCalculator';
import { toast } from 'react-toastify';

const containerVariants = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.1 } }
};

const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  show: { y: 0, opacity: 1, transition: { type: "spring", stiffness: 100 } }
};

const modulesData = [
  {
    slug: "working-class-foundation",
    title: "WORKING CLASS FOUNDATION",
    updatedAt: "October 2023",
    icon: "Home",
    status: "Directive 01",
    color: "text-yellow-electric",
    description: "Rebuilding the American working class as the core foundation of the country, shifting power away from the ultra-wealthy and empowering the backbone of our nation.",
    progress: 95,
    sponsor: "Economic Equity Council",
    revisions: 14,
    content: "The Working Class Foundation directive seeks to restructure the fundamental power dynamics of the American economy. By ensuring fair wages, strengthening workers' rights to organize, and prioritizing domestic manufacturing over cheap foreign labor, we restore the dignity of work. A strong nation requires a strong middle class, built not on financial speculation, but on tangible productivity and equitable wealth distribution."
  },
  {
    slug: "political-reform",
    title: "POLITICAL REFORM",
    updatedAt: "October 2023",
    icon: "Vote",
    status: "Directive 02",
    color: "text-yellow-electric",
    description: "Detailing the immediate need to overturn Citizens United, eliminate corrupt money from politics, and establish strict age caps and term limits for elected officials.",
    progress: 88,
    sponsor: "Civic Infrastructure Guild",
    revisions: 9,
    content: "Our political systems have been compromised by corporate lobbying and dark money. This directive demands the immediate repeal of Citizens United and the implementation of publicly funded elections. To maintain an agile and forward-thinking government, we propose strict term limits and an age cap for all federal elected officials to ensure representation reflects the current and future generations, rather than the entrenched interests of the past."
  },
  {
    slug: "the-automation-dividend-and-taxation",
    title: "THE AUTOMATION DIVIDEND & TAXATION",
    updatedAt: "October 2023",
    icon: "Cpu",
    status: "Directive 03",
    color: "text-yellow-electric",
    description: "Implementing a Negative Income Tax system funded by returning taxes on the ultra-rich and corporations to 1950s levels, closing avoidance loopholes, and returning generated wealth as a technological dividend.",
    progress: 85,
    sponsor: "Technological Advisory Board",
    revisions: 12,
    content: "As artificial intelligence and robotics displace traditional labor, the wealth generated by these efficiencies must not be concentrated solely in the hands of a few tech conglomerates. By adjusting corporate tax rates and closing loopholes, we fund 'The American Tax Credit'—a baseline Negative Income Tax ensuring every citizen receives a dividend from the nation's technological progress. This is the bedrock of economic security in the 21st century."
  },
  {
    slug: "future-infrastructure",
    title: "FUTURE INFRASTRUCTURE",
    updatedAt: "October 2023",
    icon: "Zap",
    status: "Directive 04",
    color: "text-yellow-electric",
    description: "Forward-thinking investments in renewable energy systems, futuristic high-speed train networks, and American-built, long-lasting housing programs for a modernized foundation.",
    progress: 60,
    sponsor: "Economic Equity Council",
    revisions: 8,
    content: "A nation is only as strong as its infrastructure. We propose massive investments in modernizing the power grid, transitioning to fully sustainable energy, and constructing a high-speed rail network connecting major economic hubs. Furthermore, federal initiatives will incentivize the development of durable, affordable, and technologically integrated housing, revitalizing American communities and lowering the cost of living."
  }
];

const DirectiveDetail = () => {
  const handleShareDirective = () => {
    navigator.clipboard.writeText(window.location.href).then(() => {
      toast('Configuration link copied to clipboard', { toastId: "clipboard-share",
        position: "bottom-center",
        autoClose: 2000,
        hideProgressBar: true,
        closeOnClick: true,
        pauseOnHover: false,
        draggable: false,
        className: 'bg-void border border-yellow-electric/20 text-yellow-electric font-mono text-xs uppercase tracking-widest text-center',
      });
    }).catch(err => {
      console.error('Failed to copy link', err);
    });
  };

  const { directiveSlug } = useParams();
  const [articles, setArticles] = useState([]);
  const [loadingArticles, setLoadingArticles] = useState(false);

  const { scrollYProgress } = useScroll();

  useEffect(() => {
    return () => {
      scrollYProgress.destroy();
    };
  }, [scrollYProgress]);
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });


  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const [directive, setDirective] = useState(null);
  const [isValidating, setIsValidating] = useState(true);

  useEffect(() => {
    const handleSWRUpdate = (e) => {
      if (e.detail?.endpoint === 'posts' && e.detail.newData) {
        setArticles(e.detail.newData);
      }
    };
    window.addEventListener('swr-update', handleSWRUpdate);
    return () => window.removeEventListener('swr-update', handleSWRUpdate);
  }, []);


  useEffect(() => {
    if (!directiveSlug) {
      setIsValidating(false);
      return;
    }
    const found = modulesData.find(d => d?.slug === directiveSlug);
    if (found) {
      setDirective(found);
    } else {
      console.warn('Invalid directive parameter detected');
    }
    setIsValidating(false);
  }, [directiveSlug]);

  useEffect(() => {
    let isMounted = true;
    if (directive) {
      const fetchArticles = async () => {
        setLoadingArticles(true);
        try {
          const cacheKey = 'posts-20-null';
          const cachedItem = sessionStorage.getItem(cacheKey);
          if (cachedItem) {
            try {
              const parsed = JSON.parse(cachedItem);
              if (isMounted) {
                setArticles(parsed.data);
                setLoadingArticles(false);
              }
            } catch (e) { /* ignore */ }
          }

          const posts = await getLatestPosts(20);
          if (isMounted) {
            setArticles(posts);
          }
        } catch (err) {
          console.error("Failed to fetch articles:", err);
        } finally {
          if (isMounted) setLoadingArticles(false);
        }
      };
      fetchArticles();
    }
    return () => { isMounted = false; };

  }, [directive]);

  const relatedArticles = useMemo(() => {
    if (!directive || articles.length === 0) return [];

    // Simulate mapping matching (same logic as Platform.jsx)
    const exactMatches = articles.filter(post => {
      const moduleTitle = directive.title.toLowerCase();
      const keywords = moduleTitle.split(' ').filter(w => w.length > 3);

      const postTitle = (post.title?.rendered || '').toLowerCase();
      const postContent = (post.content?.rendered || '').toLowerCase();

      return keywords.some(kw => postTitle.includes(kw) || postContent.includes(kw)) || directive.status === 'Directive 01' || directive.status === 'Directive 02';
    });
    return exactMatches.slice(0, 4);
  }, [directive, articles]);

  const readingTime = useMemo(() => {
    if (!directive || !directive.content) return 1;
    const words = directive.content.trim().split(/\s+/).length;
    return Math.max(1, Math.ceil(words / 200));
  }, [directive]);

  if (isValidating) {
    return (
      <div className="min-h-screen bg-void pt-32 pb-20 px-6 flex items-center justify-center bg-grid relative">

      <motion.div
        className="fixed top-0 left-0 right-0 h-[2px] bg-yellow-electric z-[9999]"
        style={{ scaleX, transformOrigin: '0%' }}
      />

      <Helmet>
          <title>Validating Directive | James Ellars</title>
          <meta name="robots" content="noindex" />
        </Helmet>
        <div className="deco-frame border border-yellow-electric/20 p-12 text-center max-w-md bg-surface">
          <div className="w-8 h-8 border-2 border-yellow-electric border-t-transparent rounded-full animate-spin mx-auto mb-6"></div>
          <h1 className="tracking-[0.2em] uppercase font-deco font-normal text-xl text-yellow-electric mb-4">
            Decrypting Transmission
          </h1>
        </div>
      </div>
    );
  }

  if (!directive) {
    return (
      <div className="min-h-screen bg-void pt-32 pb-20 px-6 flex items-center justify-center bg-grid relative">
        <Helmet>
          <title>Directive Not Found | James Ellars</title>
          <meta name="robots" content="noindex" />
        </Helmet>
        <div className="deco-frame border border-yellow-electric/20 p-12 text-center max-w-md bg-surface">
          <SafeIcon name="AlertTriangle" className="w-12 h-12 text-yellow-electric mx-auto mb-6" />
          <h1 className="tracking-[0.2em] uppercase font-deco font-normal text-xl text-yellow-electric mb-4">
            Transmission Interrupted
          </h1>
          <p className="diagnostic-text mb-8 flex flex-wrap justify-center items-center gap-1 leading-relaxed min-w-0 break-words">
            <span className="shrink-0">The requested directive could not be located in our intelligence index.</span>
            <span className="diagnostic-param min-w-0 break-words leading-relaxed">[{directiveSlug}]</span>
          </p>
          <Link
            to="/platform"
            className="border border-yellow-electric/20 text-yellow-electric hover:bg-yellow-electric/10 px-6 py-3 text-xs tracking-widest uppercase transition-colors inline-block"
          >
            {'<- Return to Platform Core'}
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className={`min-h-screen bg-void pt-32 pb-20 relative overflow-hidden blueprint-overlay bg-grid opacity-duration ${!loadingArticles && directive ? 'opacity-100' : 'opacity-0'}`}>
      <motion.div
        className="fixed top-0 left-0 right-0 h-[2px] bg-yellow-electric z-[9999]"
        style={{ scaleX, transformOrigin: '0%' }}
      />

      <Helmet>
        <title>{`${directive.title} Policy | James Ellars`}</title>
        <meta name="description" content={directive.description} />
      </Helmet>

      <div className="max-w-4xl mx-auto px-6 relative z-10">
        <Link to="/platform" className="inline-flex items-center text-yellow-electric text-xs uppercase tracking-widest hover:text-white transition-colors mb-12 border border-yellow-electric/20 px-4 py-2 hover:bg-yellow-electric/10">
          <SafeIcon name="ArrowLeft" className="w-4 h-4 mr-2" />
          Back to Directives
        </Link>

        <motion.div variants={containerVariants} initial="hidden" animate="show">
          <motion.div variants={itemVariants} className="mb-12 deco-frame p-6 sm:p-10 border border-white/10 bg-surface min-w-0 break-words">
            <div className="flex items-center gap-4 mb-6">
              <div className="w-16 h-16 bg-surface border border-white/10 flex items-center justify-center rounded-sm">
                <SafeIcon name={directive.icon} className={`w-6 h-6 ${directive.color}`} />
              </div>
              <span className="text-[10px] text-white font-mono uppercase tracking-[0.2em] font-bold bg-white/5 px-3 py-1 border border-white/10 h-fit">
                {directive.status}
              </span>
            </div>
            <h1 className="font-editorial font-black text-4xl md:text-6xl text-white leading-tight mb-2">
              {directive.title}
            </h1>
            {directive.updatedAt && (
              <div className="text-text-muted text-xs font-mono uppercase tracking-widest mb-6">
                Updated: {directive.updatedAt}
              </div>
            )}

            <p className="text-xl text-yellow-electric font-light max-w-3xl leading-relaxed mb-6">
              {directive.description}
            </p>
            <div className="font-mono text-xs text-zinc-600 uppercase tracking-widest mt-4">
              EST. READING TIME: {readingTime} MIN
            </div>

          </motion.div>

          <div className="deco-divider mb-12"></div>

          <motion.div variants={itemVariants} className="prose prose-invert prose-yellow max-w-none mb-16 deco-frame p-6 sm:p-10 border border-white/10 bg-surface min-w-0 break-words">
            <p className="text-text-muted text-lg leading-relaxed">
              {directive.content}
            </p>
          </motion.div>

          {directive.status === 'Directive 03' && (
            <motion.div variants={itemVariants} className="mb-16">
              <AutomationCalculator />
            </motion.div>
          )}

          <motion.div variants={itemVariants} className="bg-surface border border-white/10 p-6 sm:p-10 rounded-sm mb-16 deco-frame min-w-0 break-words">
            <h3 className="tracking-[0.2em] uppercase font-deco font-normal text-xs text-yellow-electric mb-6">
              Implementation Metrics
            </h3>
            <div className="space-y-6">
              <div className="flex justify-between items-center text-xs font-mono text-gray-600">
                <span>Public Consensus</span>
                <span className="text-[#4ade80]">{directive.progress}%</span>
              </div>
              <div className="w-full bg-void h-2 rounded-sm overflow-hidden border border-white/5">
                <div
                  className="h-full bg-[#4ade80] shadow-[0_0_10px_rgba(74,222,128,0.5)] transition-all duration-1000"
                  style={{ width: `${directive.progress}%` }}
                ></div>
              </div>
              <div className="flex justify-between text-[10px] font-mono text-gray-600 uppercase tracking-widest mt-4">
                <span>Sponsor: {directive.sponsor}</span>
                <span>Revisions: {directive.revisions}</span>
              </div>
            </div>
            <div className="mt-6 flex justify-end">
              <button
                onClick={handleShareDirective}
                className="border border-yellow-electric/30 text-yellow-electric text-xs tracking-widest uppercase hover:bg-yellow-electric/10 transition-colors px-4 py-2"
              >
                Share Configuration
              </button>
            </div>

          </motion.div>

          <motion.div variants={itemVariants}>
            <h3 className="tracking-[0.2em] uppercase font-deco font-normal text-xs text-yellow-electric mb-6 flex items-center gap-3">
              <div className="w-2 h-2 bg-yellow-electric animate-pulse"></div>
              Related Transmissions
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {loadingArticles ? (
                <div className="col-span-full font-mono text-xs text-zinc-600 uppercase tracking-widest p-4 border border-white/5 bg-white/5">
                  [DISPATCH_BUFFER_ACTIVE]
                </div>
              ) : relatedArticles.length > 0 ? (
                relatedArticles.map((post, i) => (
                  <Link key={post.id || i} to={`/articles/${post.slug}`} className="block group">
                    <div className="p-6 border border-white/10 bg-white/5 hover:border-yellow-electric hover:bg-yellow-electric/10 transition-colors h-full flex flex-col">
                      <h4 className="font-editorial text-lg text-white group-hover:text-yellow-electric transition-colors mb-4 line-clamp-2">
                        {stripHtml(post.title.rendered)}
                      </h4>
                      <span className="mt-auto text-[10px] font-mono text-gray-600 uppercase flex items-center">
                        Read Transmission <SafeIcon name="ArrowRight" className="w-3 h-3 ml-2" />
                      </span>
                    </div>
                  </Link>
                ))
              ) : (
                <div className="col-span-full text-xs text-zinc-600 font-mono tracking-widest p-4 border border-white/5 bg-white/5 uppercase">
                  Intelligence gathering in progress. Transmissions forthcoming.
                </div>
              )}
            </div>
          </motion.div>

        </motion.div>
      </div>
    </div>
  );
};

export default DirectiveDetail;
